### ISSUE TITLE
When TokenAuthListener is enabled, it blocks KeycloakController methods

### ISSUE THREAD

**Issue by szymonmalok** [mainick/KeycloakClientBundle#23]
Bunde works great, however during the implementation we have found one potential improvement.

When Mainick\KeycloakClientBundle\EventSubscriber\TokenAuthListener is configured in services, opening route /auth/keycloak/connect ends up in **Token not found** message.

Should ExcludeTokenValidationAttribute attribute be added to connect method in KeycloakController or is it recommended to use own controller for that ?

**Comment by mainick** [comment]
The best solution is to add the `ExcludeTokenValidationAttribute` attribute to the `connect` method in `KeycloakController`. I will release a bugfix as soon as possible.
