### ISSUE TITLE
default_target_route_name used as an URL instead of a route name

### ISSUE THREAD

**Issue by gubug** [mainick/KeycloakClientBundle#24]
in `KeycloakController` calls to 
`$this->redirect($defaultTargetRouteName)`
should be 
`$this->redirectToRoute($defaultTargetRouteName)`

**Comment by mainick** [comment]
It has already been solved with this commit https://github.com/mainick/KeycloakClientBundle/commit/47f30bd77132a8f3df3341a0e843baf3df0e5e7e
