### ISSUE TITLE
KeycloakResourceOwner::getRoles wrong typing

### ISSUE THREAD

**Issue by CvekCoding** [mainick/KeycloakClientBundle#28]
Hello.
I see you have a problem with typing in `KeycloakResourceOwner::getRoles()` method:
```
$roles = $this->getRealRoles();
return [...$roles, ...$this->getClientRoles($client_id)];
```
`$this->getRealRoles() ` may return null according to its signature, and in this case return statement will fail, because it requires traversable type.

**Comment by mainick** [comment]
closed by new release 2.2.1 https://github.com/mainick/KeycloakClientBundle/releases/tag/2.2.1
