### ISSUE TITLE
Question: what if refresh token expired?

### ISSUE THREAD

**Issue by CvekCoding** [mainick/KeycloakClientBundle#30]
Hello.
Looking through the code, I do not understand how the system should react if the token could not be refreshed. As i see in a code, this case is not completely handled - as a result, the exception "Could not load a KeycloakUser without an AccessToken" is thrown, because null is passed to the method `\Mainick\KeycloakClientBundle\Security\User\KeycloakUserProvider::loadUserByIdentifier`.

It seems to me that in this case (cant refresh token for some reason) it would be correct to redirect the user to the authentication page of keycloak, as it is done at the very beginning, when user does not have a session yet.

What do you think about this?

**Comment by mainick** [comment]
Thanks for the heads up. I'll work on it myself today

**Comment by mainick** [comment]
Hi @CvekCoding ,
in the new release 2.2.3, I will release a fix to handle the use case you indicated, throwing the `AuthenticationException` exception.

A clarification on this, it will be the Symfony security system that will handle the authentication failure.
The exception is caught by the Symfony firewall that will call the authenticator's `start()` method, which from the configuration reported in the README is in `KeycloakAuthenticationEntryPoint`, which manages the redirection.
So I suggest you review your [firewall and authenticator configuration](https://github.com/mainick/KeycloakClientBundle?tab=readme-ov-file#security-configuration) to get the desired behavior.

Also, I added AJAX request handling and logging if it can be useful for debugging.
